name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    needs: Train
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image from registry
        run: docker pull shashankpatil721/cicd_repo:$GITHUB_SHA

      - name: Run Docker container
        run: docker run shashankpatil721/cicd_repo:$GITHUB_SHA

      - name: Check test result
        run: |
          score=$(docker logs $(docker ps -lq) | grep "score")
          if [ $(echo "$score > 0.50" | bc -l) -eq 1 ]; then
            exit 0
          else
            exit 1
          fi
